config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

# Account Signup
get 'cwa_accountsignup/:project_id', :to => 'cwa_accountsignup#index'
get 'cwa_accountsignup/:project_id/user_info', :to => 'cwa_accountsignup#user_info'
match 'cwa_accountsignup/:project_id/create', :to => 'cwa_accountsignup#create', :via => :post
match 'cwa_accountsignup/:project_id/set_shell', :to => 'cwa_accountsignup#set_shell', :via => :post
match 'cwa_accountsignup/:project_id/delete', :to => 'cwa_accountsignup#delete', :via => :post

# Group Manager
get 'cwa_groups/:project_id', :to => 'cwa_groups#index'
get 'cwa_groups/:project_id/all', :to => 'cwa_groups#groups'
get 'cwa_groups/:project_id/show/:group_name', :to => 'cwa_groups#show', group_name: /[a-zA-Z0-9\-\._\ ]{2,20}/
get 'cwa_groups/:project_id/create', :to => 'cwa_groups#create'
match 'cwa_groups/:project_id/add', :to => 'cwa_groups#add', :via => :post
match 'cwa_groups/:project_id/delete', :to => 'cwa_groups#delete', :via => :post
match 'cwa_groups/:project_id/disband', :to => 'cwa_groups#disband', :via => :post
match 'cwa_groups/:project_id/save_request', :to => 'cwa_groups#save_request', :via => :post
match 'cwa_groups/:project_id/delete_request', :to => 'cwa_groups#delete_request', :via => :post
match 'cwa_groups/:project_id/allow_join', :to => 'cwa_groups#allow_join', :via => :post
match 'cwa_groups/:project_id/create_group', :to => 'cwa_groups#create_group', :via => :post
match 'cwa_groups/:project_id/delete_group', :to => 'cwa_groups#delete_group', :via => :post

# Job Manager
get 'cwa_jobmanager/:project_id', :to => 'cwa_jobmanager#index'
get 'cwa_jobmanager/:project_id/all', :to => 'cwa_jobmanager#alljobs'
get 'cwa_jobmanager/:project_id/current_jobs', :to => 'cwa_jobmanager#current_jobs'
get 'cwa_jobmanager/:project_id/queue_status', :to => 'cwa_jobmanager#queue_status'
get 'cwa_jobmanager/:project_id/job_history', :to => 'cwa_jobmanager#job_history'
match 'cwa_jobmanager/:project_id/submit', :to => 'cwa_jobmanager#submit', :via => :post
match 'cwa_jobmanager/:project_id/delete', :to => 'cwa_jobmanager#delete', :via => :post

# Applications
get 'cwa_applications/:project_id', :to => 'cwa_applications#index', :as => :cwa_applications
get 'cwa_applications/:project_id/new', :to => 'cwa_applications#new'
get 'cwa_applications/:project_id/:id', :to => 'cwa_applications#display'
get 'cwa_applications/:project_id/edit/:id', :to => 'cwa_applications#show', :as => :cwa_application
match 'cwa_applications/:project_id/new', :to => 'cwa_applications#new', :via => :post
match 'cwa_applications/:project_id/edit/:id', :to => 'cwa_applications#update', :via => :put
match 'cwa_applications/:project_id/delete/:id', :to => 'cwa_applications#delete', :via => :delete

# Allocations
get 'cwa_allocations/:project_id', :to => 'cwa_allocations#index'
get 'cwa_allocations/:project_id/admin', :to => 'cwa_allocations#admin'
get 'cwa_allocations/:project_id/form', :to => 'cwa_allocations#form'
match 'cwa_allocations/:project_id/submit', :to => 'cwa_allocations#submit', :via => :post
match 'cwa_allocations/:project_id/delete', :to => 'cwa_allocations#delete', :via => :post
match 'cwa_allocations/:project_id/update', :to => 'cwa_allocations#update', :via => :post

# Default
get 'cwa_default/:project_id/not_activated', :to => 'cwa_default#not_activated'
get 'cwa_default/:project_id/unavailable', :to => 'cwa_default#unavailable'
get 'cwa_default/:project_id/authorization', :to => 'cwa_default#authorization'

# Browser
get 'cwa_browser/:project_id', :to => 'cwa_browser#index'

#
# Try to define REST api like so:
#
# ./<home|shares|work>/path/to/file/<method>
#
get 'cwa_browser/:project_id/download/:fid',
  :to => 'cwa_browser#get'

get 'cwa_browser/:project_id/downloadzip/:fid',
  :to => 'cwa_browser#get_zip'

# Creating new text files
post 'cwa_browser/:project_id/*share/create',
  :to => 'cwa_browser#create',
  :share => /(home|shares|work)/

post 'cwa_browser/:project_id/*share/*path/create',
  :to => 'cwa_browser#create',
  :share => /(home|shares|work)/
#  :path => /[^\0]+/

# file move goodness
# Case where we're moving from a share/path to the root of a share
post 'cwa_browser/:project_id/*share/*path/move/*target_share',
  :to => 'cwa_browser#move',
  :share => /(home|shares|work)/,
  :target_share => /(home|shares|work)/
  #:path => /[^\0]+/

# Case where we're moving from the share/path to a share/path
post 'cwa_browser/:project_id/*share/*path/move/*target_share/*target_path',
  :to => 'cwa_browser#move',
  :share => /(home|shares|work)/,
  :target_share => /(home|shares|work)/,
  #:path => /[^\0]+/,
  :target_path => /[^\0]+/

# file copy goodness
post 'cwa_browser/:project_id/*share/*path/copy/*target_share',
  :to => 'cwa_browser#copy',
  :share => /(home|shares|work)/,
  :target_share => /(home|shares|work)/
  #:path => /[^\0]+/

# Case where we're moving from the share/path to a share/path
post 'cwa_browser/:project_id/*share/*path/copy/*target_share/*target_path',
  :to => 'cwa_browser#copy',
  :share => /(home|shares|work)/,
  :target_share => /(home|shares|work)/,
  #:path => /[^\0]+/,
  :target_path => /[^\0]+/

get 'cwa_browser/:project_id/op_status',
  :to => 'cwa_browser#op_status'

# Download methods
get 'cwa_browser/:project_id/download/:fid',
  :to => 'cwa_browser#get'

get 'cwa_browser/:project_id/downloadzip/:fid',
  :to => 'cwa_browser#get_zip'

post 'cwa_browser/:project_id/*share/*path/download',
  :to => 'cwa_browser#download',
  :share => /(home|shares|work)/

# Upload methods
post 'cwa_browser/:project_id/*share/upload',
  :to => 'cwa_browser#upload',
  :share => /(home|shares|work)/

post 'cwa_browser/:project_id/*share/*dir/upload',
  :to => 'cwa_browser#upload',
  #:path => /[^\0]+/,
  :share => /(home|shares|work)/

# Make directories
post 'cwa_browser/:project_id/*share/mkdir/*new_dir',
  :to => 'cwa_browser#mkdir',
  :new_dir => /[^\0]+/,
  :share => /(home|shares|work)/

post 'cwa_browser/:project_id/*share/*path/mkdir/*new_dir',
  :to => 'cwa_browser#mkdir',
#  :path => /[^\0]+/,
  :new_dir => /[^\0]+/,
  :share => /(home|shares|work)/

# Delete a file
post 'cwa_browser/:project_id/*share/*path/delete',
  :to => 'cwa_browser#delete',
  #:path => /[^\0]+/,
  :share => /(home|shares|work)/

# Rename a file
post 'cwa_browser/:project_id/*share/*file/rename/*new_name', 
  :to => 'cwa_browser#rename',
  :file => /[^\0]+/,
  :new_name => /[^\0]+/,
  :share => /(home|shares|work)/

# Tail a file
post 'cwa_browser/:project_id/*share/*file/tail', 
  :to => 'cwa_browser#tail',
  :file => /[^\0]+/,
  :share => /(home|shares|work)/

# Display a path
get 'cwa_browser/:project_id/*share/*dir', :to => 'cwa_browser#index',
  :share => /(home|shares|work)/,
  :dir => /[^\0]+/

# Display a path at the base of a share
get 'cwa_browser/:project_id/*share', :to => 'cwa_browser#index',
  :share => /(home|work)/

# Stats browser
get 'cwa_stats/:project_id', :to => 'cwa_stats#index'
#get 'cwa_stats/system/:project_id', :to => 'cwa_stats#ganglia'
#resources 'cwa_stats/:project_id', :only => [:index, :new, :edit, :create, :delete, :show, :update]

app/views/projects/show.html.erb
<div class="contextual">
  <% if User.current.allowed_to?(:add_subprojects, @project) %>
    <%= link_to l(:label_subproject_new), new_project_path(:parent_id => @project), :class => 'icon icon-add' %>
  <% end %>
  <% if User.current.allowed_to?(:close_project, @project) %>
    <% if @project.active? %>
      <%= link_to l(:button_close), close_project_path(@project), :data => {:confirm => l(:text_are_you_sure)}, :method => :post, :class => 'icon icon-lock' %>
    <% else %>
      <%= link_to l(:button_reopen), reopen_project_path(@project), :data => {:confirm => l(:text_are_you_sure)}, :method => :post, :class => 'icon icon-unlock' %>
    <% end %>
  <% end %>
</div>

<h2><%=l(:label_overview)%></h2>

<% unless @project.active? %>
  <p class="warning"><span class="icon icon-lock"><%= l(:text_project_closed) %></span></p>
<% end %>

<div class="splitcontentleft">
  <% if @project.description.present? %>
  <div class="wiki">
    <%= textilizable @project.description %>
  </div>
  <% end %>
  <ul>
  <% unless @project.homepage.blank? %>
    <li><%=l(:field_homepage)%>: <%= link_to h(@project.homepage), @project.homepage %></li>
  <% end %>
  <% if @subprojects.any? %>
    <li><%=l(:label_subproject_plural)%>:
      <%= @subprojects.collect{|p| link_to p, project_path(p)}.join(", ").html_safe %></li>
  <% end %>
  <% @project.visible_custom_field_values.each do |custom_value| %>
  <% if !custom_value.value.blank? %>
     <li><%=h custom_value.custom_field.name %>: <%=h show_value(custom_value) %></li>
  <% end %>
  <% end %>
  </ul>

  <% if User.current.allowed_to?(:view_issues, @project) %>
  <div class="issues box">
    <h3><%=l(:label_issue_tracking)%></h3>
    <ul>
    <% for tracker in @trackers %>
      <li><%= link_to h(tracker.name), project_issues_path(@project, :set_filter => 1, :tracker_id => tracker.id) %>:
          <%= l(:label_x_open_issues_abbr_on_total, :count => @open_issues_by_tracker[tracker].to_i,
                                                    :total => @total_issues_by_tracker[tracker].to_i) %>
      </li>
    <% end %>
    </ul>
    <p>
      <%= link_to l(:label_issue_view_all), project_issues_path(@project, :set_filter => 1) %>
      <% if User.current.allowed_to?(:view_calendar, @project, :global => true) %>
        | <%= link_to l(:label_calendar), project_calendar_path(@project) %>
      <% end %>
      <% if User.current.allowed_to?(:view_gantt, @project, :global => true) %>
        | <%= link_to l(:label_gantt), project_gantt_path(@project) %>
      <% end %>
    </p>
  </div>
  <% end %>
  <%= call_hook(:view_projects_show_left, :project => @project) %>
</div>

<div class="splitcontentright">
  <% @user = CwaIpaUser.new %>
  <% if @user.provisioned? %>
    <div class="box">
    <%= render :partial => "cwa_default/usagestats" %>
    </div>
  <% end %>
  <% if @news.any? && authorize_for('news', 'index') %>
  <div class="news box">
    <h3><%=l(:label_news_latest)%></h3>
    <%= render :partial => 'news/news', :collection => @news %>
    <p><%= link_to l(:label_news_view_all), project_news_index_path(@project) %></p>
  </div>
  <% end %>
  <%= call_hook(:view_projects_show_right, :project => @project) %>
</div>

<% content_for :header_tags do %>
<%= auto_discovery_link_tag(:atom, {:controller => 'activities', :action => 'index', :id => @project, :format => 'atom', :key => User.current.rss_key}) %>
<% end %>

<% html_title(l(:label_overview)) -%>